schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

"A connection to a list of items."
type AuthorConnection {
  "A list of edges."
  edges: [AuthorEdge!]
  "A flattened list of the nodes"
  nodes: [Author!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int!
}

"A connection to a list of items."
type BlogPostConnection {
  "A list of edges."
  edges: [BlogPostEdge!]
  "A flattened list of the nodes"
  nodes: [BlogPost!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int!
}

"A connection to a list of items."
type CommentConnection {
  "A list of edges."
  edges: [CommentEdge!]
  "A flattened list of the nodes"
  nodes: [Comment!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int!
}

"A connection to a list of items."
type TagConnection {
  "A list of edges."
  edges: [TagEdge!]
  "A flattened list of the nodes"
  nodes: [Tag!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int!
}

type AuthorEdge {
  "The item at the end of the edge."
  node: Author!
  "A cursor for use in pagination."
  cursor: String!
}

type BlogPostEdge {
  "The item at the end of the edge."
  node: BlogPost!
  "A cursor for use in pagination."
  cursor: String!
}

type CommentEdge {
  "The item at the end of the edge."
  node: Comment!
  "A cursor for use in pagination."
  cursor: String!
}

type TagEdge {
  "The item at the end of the edge."
  node: Tag!
  "A cursor for use in pagination."
  cursor: String!
}

type Query {
  authors(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: AuthorFilterInput
    order: [AuthorSortInput!]
  ): AuthorConnection!
  authorById(id: Int!): Author
  posts(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: BlogPostFilterInput
    order: [BlogPostSortInput!]
  ): BlogPostConnection!
  postById(id: Int!): BlogPost
  tags(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: TagFilterInput
    order: [TagSortInput!]
  ): TagConnection!
}

type Mutation {
  createAuthor(input: CreateAuthorInput!): CreateAuthorPayload!
  addComment(input: AddCommentInput!): AddCommentPayload!
  createPost(input: CreatePostInput!): CreatePostPayload!
  updatePost(input: UpdatePostInput!): UpdatePostPayload!
  deletePost(input: DeletePostInput!): DeletePostPayload!
  createTag(input: CreateTagInput!): CreateTagPayload!
  deleteTag(input: DeleteTagInput!): DeleteTagPayload!
}

type Subscription {
  onCommentAdded(postId: Int!): Comment!
  onPostPublished: BlogPost!
}

type Author {
  posts(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: BlogPostFilterInput
    order: [BlogPostSortInput!]
  ): BlogPostConnection!
  id: Int!
  name: String!
  bio: String
  createdAt: DateTime!
}

type Comment {
  author: Author!
  post: BlogPost!
  id: Int!
  text: String!
  createdAt: DateTime!
  blogPostId: Int!
  authorId: Int!
}

type BlogPost {
  author: Author!
  comments(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: CommentFilterInput
    order: [CommentSortInput!]
  ): CommentConnection!
  tags(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: TagFilterInput
    order: [TagSortInput!]
  ): TagConnection!
  id: Int!
  title: String!
  slug: String!
  body: String!
  status: PostStatus!
  createdAt: DateTime!
  publishedAt: DateTime
  authorId: Int!
}

input AuthorFilterInput {
  and: [AuthorFilterInput!]
  or: [AuthorFilterInput!]
  id: IntOperationFilterInput
  name: StringOperationFilterInput
  bio: StringOperationFilterInput
  createdAt: DateTimeOperationFilterInput
}

input AuthorSortInput {
  id: SortEnumType
  name: SortEnumType
  bio: SortEnumType
  createdAt: SortEnumType
}

input BlogPostFilterInput {
  and: [BlogPostFilterInput!]
  or: [BlogPostFilterInput!]
  id: IntOperationFilterInput
  title: StringOperationFilterInput
  slug: StringOperationFilterInput
  body: StringOperationFilterInput
  status: PostStatusOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  publishedAt: DateTimeOperationFilterInput
  authorId: IntOperationFilterInput
}

input BlogPostSortInput {
  id: SortEnumType
  title: SortEnumType
  slug: SortEnumType
  body: SortEnumType
  status: SortEnumType
  createdAt: SortEnumType
  publishedAt: SortEnumType
  authorId: SortEnumType
}

input TagFilterInput {
  and: [TagFilterInput!]
  or: [TagFilterInput!]
  id: IntOperationFilterInput
  name: StringOperationFilterInput
}

input TagSortInput {
  id: SortEnumType
  name: SortEnumType
}

type AuthorNotFoundError implements Error {
  message: String!
  authorId: Int!
}

type PostNotFoundError implements Error {
  message: String!
  postId: Int!
}

type SlugAlreadyInUseError implements Error {
  message: String!
  slug: String!
}

type TagNotFoundError implements Error {
  message: String!
  tagId: Int!
}

input CommentFilterInput {
  and: [CommentFilterInput!]
  or: [CommentFilterInput!]
  id: IntOperationFilterInput
  text: StringOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  blogPostId: IntOperationFilterInput
  authorId: IntOperationFilterInput
}

input CommentSortInput {
  id: SortEnumType
  text: SortEnumType
  createdAt: SortEnumType
  blogPostId: SortEnumType
  authorId: SortEnumType
}

input IntOperationFilterInput {
  eq: Int
  neq: Int
  in: [Int]
  nin: [Int]
  gt: Int
  ngt: Int
  gte: Int
  ngte: Int
  lt: Int
  nlt: Int
  lte: Int
  nlte: Int
}

input StringOperationFilterInput {
  and: [StringOperationFilterInput!]
  or: [StringOperationFilterInput!]
  eq: String
  neq: String
  contains: String
  ncontains: String
  in: [String]
  nin: [String]
  startsWith: String
  nstartsWith: String
  endsWith: String
  nendsWith: String
}

input DateTimeOperationFilterInput {
  eq: DateTime
  neq: DateTime
  in: [DateTime]
  nin: [DateTime]
  gt: DateTime
  ngt: DateTime
  gte: DateTime
  ngte: DateTime
  lt: DateTime
  nlt: DateTime
  lte: DateTime
  nlte: DateTime
}

enum SortEnumType {
  ASC
  DESC
}

input PostStatusOperationFilterInput {
  eq: PostStatus
  neq: PostStatus
  in: [PostStatus!]
  nin: [PostStatus!]
}

interface Error {
  message: String!
}

"The `DateTime` scalar type represents a date and time with time zone offset information."
scalar DateTime

"Information about pagination in a connection."
type PageInfo {
  "Indicates whether more edges exist following the set defined by the clients arguments."
  hasNextPage: Boolean!
  "Indicates whether more edges exist prior the set defined by the clients arguments."
  hasPreviousPage: Boolean!
  "When paginating backwards, the cursor to continue."
  startCursor: String
  "When paginating forwards, the cursor to continue."
  endCursor: String
  "A list of cursors to continue paginating forwards."
  forwardCursors: [PageCursor!]!
  "A list of cursors to continue paginating backwards."
  backwardCursors: [PageCursor!]!
}

type Tag {
  id: Int!
  name: String!
}

enum PostStatus {
  DRAFT
  PUBLISHED
}

"A cursor that points to a specific page."
type PageCursor {
  "The page number."
  page: Int!
  "The cursor."
  cursor: String!
}

input CreateAuthorInput {
  name: String!
  bio: String
}

type CreateAuthorPayload {
  author: Author
}

input AddCommentInput {
  postId: Int!
  authorId: Int!
  text: String!
}

union AddCommentError = AuthorNotFoundError | PostNotFoundError

type AddCommentPayload {
  comment: Comment
  errors: [AddCommentError!]
}

input CreatePostInput {
  title: String!
  body: String!
  authorId: Int!
  status: PostStatus!
  tagIds: [Int!]
}

union CreatePostError = AuthorNotFoundError | SlugAlreadyInUseError

type CreatePostPayload {
  blogPost: BlogPost
  errors: [CreatePostError!]
}

input UpdatePostInput {
  id: Int!
  title: String
  body: String
  status: PostStatus
}

union UpdatePostError = PostNotFoundError | SlugAlreadyInUseError

type UpdatePostPayload {
  blogPost: BlogPost
  errors: [UpdatePostError!]
}

input DeletePostInput {
  id: Int!
}

union DeletePostError = PostNotFoundError

type DeletePostPayload {
  blogPost: BlogPost
  errors: [DeletePostError!]
}

input CreateTagInput {
  name: String!
}

union CreateTagError = SlugAlreadyInUseError

type CreateTagPayload {
  tag: Tag
  errors: [CreateTagError!]
}

input DeleteTagInput {
  id: Int!
}

union DeleteTagError = TagNotFoundError

type DeleteTagPayload {
  tag: Tag
  errors: [DeleteTagError!]
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost(
  "The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc."
  weight: String!
) on
  | SCALAR
  | OBJECT
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | ENUM
  | INPUT_FIELD_DEFINITION

"The purpose of the `@listSize` directive is to either inform the static analysis about the size of returned lists (if that information is statically available), or to point the analysis to where to find that information."
directive @listSize(
  "The `assumedSize` argument can be used to statically define the maximum length of a list returned by a field."
  assumedSize: Int
  "The `slicingArguments` argument can be used to define which of the field's arguments with numeric type are slicing arguments, so that their value determines the size of the list returned by that field. It may specify a list of multiple slicing arguments."
  slicingArguments: [String!]
  "The `slicingArgumentDefaultValue` argument can be used to define a default value for a slicing argument, which is used if the argument is not present in a query."
  slicingArgumentDefaultValue: Int
  "The `sizedFields` argument can be used to define that the value of the `assumedSize` argument or of a slicing argument does not affect the size of a list returned by a field itself, but that of a list returned by one of its sub-fields."
  sizedFields: [String!]
  "The `requireOneSlicingArgument` argument can be used to inform the static analysis that it should expect that exactly one of the defined slicing arguments is present in a query. If that is not the case (i.e., if none or multiple slicing arguments are present), the static analysis may throw an error."
  requireOneSlicingArgument: Boolean = true
) on FIELD_DEFINITION