query GetPosts($first: Int, $after: String, $where: BlogPostFilterInput, $order: [BlogPostSortInput!]) {
  posts(first: $first, after: $after, where: $where, order: $order) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      title
      slug
      status
      createdAt
      publishedAt
      author {
        id
        name
      }
      tags(first: 10) {
        nodes {
          id
          name
        }
      }
      comments(first: 1) {
        totalCount
      }
    }
  }
}
